### ISSUE TITLE
重签IPA报错：Failed to match any available certificate for signing: No error message provided.

### ISSUE THREAD

**Issue by kkppa** [codematrixer/icertools#1]
通过个人开发者账号进行IPA重签时报错如下

Traceback (most recent call last):
  File "example.py", line 53, in <module>
    r.resign_ipa()
  File "/Users/icertools/icertools/resign.py", line 288, in resign_ipa
    local_cer_uuid = find_matching_local_certificate(cer_uuids)
  File "/Users/icertools/icertools/_utils.py", line 124, in find_matching_local_certificate
    raise RuntimeError(f"Failed to match any available certificate for signing: {error_message}")
RuntimeError: Failed to match any available certificate for signing: No error message provided.

**Comment by codematrixer** [comment]
这是find_matching_local_certificate报错，应该是没有提前安装证书吧，看下readme里Usage的前置步骤
